// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientStreaming.proto

package io.grpc.clientStreaming;

public final class ClientStreamingGrpc {
  private ClientStreamingGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientStreamingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clientStreaming.ClientStreamingRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string RequsetParm1 = 1;</code>
     */
    java.lang.String getRequsetParm1();
    /**
     * <code>string RequsetParm1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequsetParm1Bytes();
  }
  /**
   * Protobuf type {@code clientStreaming.ClientStreamingRequest}
   */
  public  static final class ClientStreamingRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:clientStreaming.ClientStreamingRequest)
      ClientStreamingRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientStreamingRequest.newBuilder() to construct.
    private ClientStreamingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientStreamingRequest() {
      requsetParm1_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientStreamingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requsetParm1_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.clientStreaming.ClientStreamingGrpc.internal_static_clientStreaming_ClientStreamingRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.clientStreaming.ClientStreamingGrpc.internal_static_clientStreaming_ClientStreamingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest.class, io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest.Builder.class);
    }

    public static final int REQUSETPARM1_FIELD_NUMBER = 1;
    private volatile java.lang.Object requsetParm1_;
    /**
     * <code>string RequsetParm1 = 1;</code>
     */
    public java.lang.String getRequsetParm1() {
      java.lang.Object ref = requsetParm1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requsetParm1_ = s;
        return s;
      }
    }
    /**
     * <code>string RequsetParm1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequsetParm1Bytes() {
      java.lang.Object ref = requsetParm1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requsetParm1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequsetParm1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requsetParm1_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequsetParm1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requsetParm1_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest)) {
        return super.equals(obj);
      }
      io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest other = (io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest) obj;

      boolean result = true;
      result = result && getRequsetParm1()
          .equals(other.getRequsetParm1());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUSETPARM1_FIELD_NUMBER;
      hash = (53 * hash) + getRequsetParm1().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code clientStreaming.ClientStreamingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:clientStreaming.ClientStreamingRequest)
        io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.clientStreaming.ClientStreamingGrpc.internal_static_clientStreaming_ClientStreamingRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.clientStreaming.ClientStreamingGrpc.internal_static_clientStreaming_ClientStreamingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest.class, io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest.Builder.class);
      }

      // Construct using io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requsetParm1_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.clientStreaming.ClientStreamingGrpc.internal_static_clientStreaming_ClientStreamingRequest_descriptor;
      }

      public io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest getDefaultInstanceForType() {
        return io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest.getDefaultInstance();
      }

      public io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest build() {
        io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest buildPartial() {
        io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest result = new io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest(this);
        result.requsetParm1_ = requsetParm1_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest) {
          return mergeFrom((io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest other) {
        if (other == io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest.getDefaultInstance()) return this;
        if (!other.getRequsetParm1().isEmpty()) {
          requsetParm1_ = other.requsetParm1_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requsetParm1_ = "";
      /**
       * <code>string RequsetParm1 = 1;</code>
       */
      public java.lang.String getRequsetParm1() {
        java.lang.Object ref = requsetParm1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requsetParm1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string RequsetParm1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequsetParm1Bytes() {
        java.lang.Object ref = requsetParm1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requsetParm1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string RequsetParm1 = 1;</code>
       */
      public Builder setRequsetParm1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requsetParm1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string RequsetParm1 = 1;</code>
       */
      public Builder clearRequsetParm1() {
        
        requsetParm1_ = getDefaultInstance().getRequsetParm1();
        onChanged();
        return this;
      }
      /**
       * <code>string RequsetParm1 = 1;</code>
       */
      public Builder setRequsetParm1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requsetParm1_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:clientStreaming.ClientStreamingRequest)
    }

    // @@protoc_insertion_point(class_scope:clientStreaming.ClientStreamingRequest)
    private static final io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest();
    }

    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientStreamingRequest>
        PARSER = new com.google.protobuf.AbstractParser<ClientStreamingRequest>() {
      public ClientStreamingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientStreamingRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientStreamingRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientStreamingRequest> getParserForType() {
      return PARSER;
    }

    public io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientStreamingReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clientStreaming.ClientStreamingReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ReplyParm1 = 1;</code>
     */
    java.lang.String getReplyParm1();
    /**
     * <code>string ReplyParm1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getReplyParm1Bytes();
  }
  /**
   * Protobuf type {@code clientStreaming.ClientStreamingReply}
   */
  public  static final class ClientStreamingReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:clientStreaming.ClientStreamingReply)
      ClientStreamingReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientStreamingReply.newBuilder() to construct.
    private ClientStreamingReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientStreamingReply() {
      replyParm1_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientStreamingReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              replyParm1_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.clientStreaming.ClientStreamingGrpc.internal_static_clientStreaming_ClientStreamingReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.clientStreaming.ClientStreamingGrpc.internal_static_clientStreaming_ClientStreamingReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply.class, io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply.Builder.class);
    }

    public static final int REPLYPARM1_FIELD_NUMBER = 1;
    private volatile java.lang.Object replyParm1_;
    /**
     * <code>string ReplyParm1 = 1;</code>
     */
    public java.lang.String getReplyParm1() {
      java.lang.Object ref = replyParm1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        replyParm1_ = s;
        return s;
      }
    }
    /**
     * <code>string ReplyParm1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReplyParm1Bytes() {
      java.lang.Object ref = replyParm1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        replyParm1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReplyParm1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, replyParm1_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReplyParm1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, replyParm1_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply)) {
        return super.equals(obj);
      }
      io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply other = (io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply) obj;

      boolean result = true;
      result = result && getReplyParm1()
          .equals(other.getReplyParm1());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REPLYPARM1_FIELD_NUMBER;
      hash = (53 * hash) + getReplyParm1().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code clientStreaming.ClientStreamingReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:clientStreaming.ClientStreamingReply)
        io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.clientStreaming.ClientStreamingGrpc.internal_static_clientStreaming_ClientStreamingReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.clientStreaming.ClientStreamingGrpc.internal_static_clientStreaming_ClientStreamingReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply.class, io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply.Builder.class);
      }

      // Construct using io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        replyParm1_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.clientStreaming.ClientStreamingGrpc.internal_static_clientStreaming_ClientStreamingReply_descriptor;
      }

      public io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply getDefaultInstanceForType() {
        return io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply.getDefaultInstance();
      }

      public io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply build() {
        io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply buildPartial() {
        io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply result = new io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply(this);
        result.replyParm1_ = replyParm1_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply) {
          return mergeFrom((io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply other) {
        if (other == io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply.getDefaultInstance()) return this;
        if (!other.getReplyParm1().isEmpty()) {
          replyParm1_ = other.replyParm1_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object replyParm1_ = "";
      /**
       * <code>string ReplyParm1 = 1;</code>
       */
      public java.lang.String getReplyParm1() {
        java.lang.Object ref = replyParm1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          replyParm1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ReplyParm1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReplyParm1Bytes() {
        java.lang.Object ref = replyParm1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          replyParm1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ReplyParm1 = 1;</code>
       */
      public Builder setReplyParm1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        replyParm1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ReplyParm1 = 1;</code>
       */
      public Builder clearReplyParm1() {
        
        replyParm1_ = getDefaultInstance().getReplyParm1();
        onChanged();
        return this;
      }
      /**
       * <code>string ReplyParm1 = 1;</code>
       */
      public Builder setReplyParm1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        replyParm1_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:clientStreaming.ClientStreamingReply)
    }

    // @@protoc_insertion_point(class_scope:clientStreaming.ClientStreamingReply)
    private static final io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply();
    }

    public static io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientStreamingReply>
        PARSER = new com.google.protobuf.AbstractParser<ClientStreamingReply>() {
      public ClientStreamingReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientStreamingReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientStreamingReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientStreamingReply> getParserForType() {
      return PARSER;
    }

    public io.grpc.clientStreaming.ClientStreamingGrpc.ClientStreamingReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clientStreaming_ClientStreamingRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clientStreaming_ClientStreamingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clientStreaming_ClientStreamingReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clientStreaming_ClientStreamingReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025clientStreaming.proto\022\017clientStreaming" +
      "\".\n\026ClientStreamingRequest\022\024\n\014RequsetPar" +
      "m1\030\001 \001(\t\"*\n\024ClientStreamingReply\022\022\n\nRepl" +
      "yParm1\030\001 \001(\t2\203\001\n\026ClientStreamingService\022" +
      "i\n\023ClientStreamingCall\022\'.clientStreaming" +
      ".ClientStreamingRequest\032%.clientStreamin" +
      "g.ClientStreamingReply\"\000(\001B.\n\027io.grpc.cl" +
      "ientStreamingB\023ClientStreamingGrpcb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_clientStreaming_ClientStreamingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_clientStreaming_ClientStreamingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clientStreaming_ClientStreamingRequest_descriptor,
        new java.lang.String[] { "RequsetParm1", });
    internal_static_clientStreaming_ClientStreamingReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_clientStreaming_ClientStreamingReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clientStreaming_ClientStreamingReply_descriptor,
        new java.lang.String[] { "ReplyParm1", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
