// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverStreaming.proto

package io.grpc.serverStreaming;

public final class ServerStreamingGrpc {
  private ServerStreamingGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServerStreamingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serverStreaming.ServerStreamingRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string RequsetParm1 = 1;</code>
     */
    java.lang.String getRequsetParm1();
    /**
     * <code>string RequsetParm1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequsetParm1Bytes();
  }
  /**
   * Protobuf type {@code serverStreaming.ServerStreamingRequest}
   */
  public  static final class ServerStreamingRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:serverStreaming.ServerStreamingRequest)
      ServerStreamingRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerStreamingRequest.newBuilder() to construct.
    private ServerStreamingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerStreamingRequest() {
      requsetParm1_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerStreamingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requsetParm1_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.serverStreaming.ServerStreamingGrpc.internal_static_serverStreaming_ServerStreamingRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.serverStreaming.ServerStreamingGrpc.internal_static_serverStreaming_ServerStreamingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest.class, io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest.Builder.class);
    }

    public static final int REQUSETPARM1_FIELD_NUMBER = 1;
    private volatile java.lang.Object requsetParm1_;
    /**
     * <code>string RequsetParm1 = 1;</code>
     */
    public java.lang.String getRequsetParm1() {
      java.lang.Object ref = requsetParm1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requsetParm1_ = s;
        return s;
      }
    }
    /**
     * <code>string RequsetParm1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequsetParm1Bytes() {
      java.lang.Object ref = requsetParm1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requsetParm1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequsetParm1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requsetParm1_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequsetParm1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requsetParm1_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest)) {
        return super.equals(obj);
      }
      io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest other = (io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest) obj;

      boolean result = true;
      result = result && getRequsetParm1()
          .equals(other.getRequsetParm1());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUSETPARM1_FIELD_NUMBER;
      hash = (53 * hash) + getRequsetParm1().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serverStreaming.ServerStreamingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serverStreaming.ServerStreamingRequest)
        io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.serverStreaming.ServerStreamingGrpc.internal_static_serverStreaming_ServerStreamingRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.serverStreaming.ServerStreamingGrpc.internal_static_serverStreaming_ServerStreamingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest.class, io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest.Builder.class);
      }

      // Construct using io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requsetParm1_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.serverStreaming.ServerStreamingGrpc.internal_static_serverStreaming_ServerStreamingRequest_descriptor;
      }

      public io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest getDefaultInstanceForType() {
        return io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest.getDefaultInstance();
      }

      public io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest build() {
        io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest buildPartial() {
        io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest result = new io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest(this);
        result.requsetParm1_ = requsetParm1_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest) {
          return mergeFrom((io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest other) {
        if (other == io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest.getDefaultInstance()) return this;
        if (!other.getRequsetParm1().isEmpty()) {
          requsetParm1_ = other.requsetParm1_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requsetParm1_ = "";
      /**
       * <code>string RequsetParm1 = 1;</code>
       */
      public java.lang.String getRequsetParm1() {
        java.lang.Object ref = requsetParm1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requsetParm1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string RequsetParm1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequsetParm1Bytes() {
        java.lang.Object ref = requsetParm1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requsetParm1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string RequsetParm1 = 1;</code>
       */
      public Builder setRequsetParm1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requsetParm1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string RequsetParm1 = 1;</code>
       */
      public Builder clearRequsetParm1() {
        
        requsetParm1_ = getDefaultInstance().getRequsetParm1();
        onChanged();
        return this;
      }
      /**
       * <code>string RequsetParm1 = 1;</code>
       */
      public Builder setRequsetParm1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requsetParm1_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:serverStreaming.ServerStreamingRequest)
    }

    // @@protoc_insertion_point(class_scope:serverStreaming.ServerStreamingRequest)
    private static final io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest();
    }

    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerStreamingRequest>
        PARSER = new com.google.protobuf.AbstractParser<ServerStreamingRequest>() {
      public ServerStreamingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerStreamingRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerStreamingRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerStreamingRequest> getParserForType() {
      return PARSER;
    }

    public io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServerStreamingReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serverStreaming.ServerStreamingReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ReplyParm1 = 1;</code>
     */
    java.lang.String getReplyParm1();
    /**
     * <code>string ReplyParm1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getReplyParm1Bytes();
  }
  /**
   * Protobuf type {@code serverStreaming.ServerStreamingReply}
   */
  public  static final class ServerStreamingReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:serverStreaming.ServerStreamingReply)
      ServerStreamingReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerStreamingReply.newBuilder() to construct.
    private ServerStreamingReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerStreamingReply() {
      replyParm1_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerStreamingReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              replyParm1_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.serverStreaming.ServerStreamingGrpc.internal_static_serverStreaming_ServerStreamingReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.serverStreaming.ServerStreamingGrpc.internal_static_serverStreaming_ServerStreamingReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply.class, io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply.Builder.class);
    }

    public static final int REPLYPARM1_FIELD_NUMBER = 1;
    private volatile java.lang.Object replyParm1_;
    /**
     * <code>string ReplyParm1 = 1;</code>
     */
    public java.lang.String getReplyParm1() {
      java.lang.Object ref = replyParm1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        replyParm1_ = s;
        return s;
      }
    }
    /**
     * <code>string ReplyParm1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReplyParm1Bytes() {
      java.lang.Object ref = replyParm1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        replyParm1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReplyParm1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, replyParm1_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReplyParm1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, replyParm1_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply)) {
        return super.equals(obj);
      }
      io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply other = (io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply) obj;

      boolean result = true;
      result = result && getReplyParm1()
          .equals(other.getReplyParm1());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REPLYPARM1_FIELD_NUMBER;
      hash = (53 * hash) + getReplyParm1().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serverStreaming.ServerStreamingReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serverStreaming.ServerStreamingReply)
        io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.serverStreaming.ServerStreamingGrpc.internal_static_serverStreaming_ServerStreamingReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.serverStreaming.ServerStreamingGrpc.internal_static_serverStreaming_ServerStreamingReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply.class, io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply.Builder.class);
      }

      // Construct using io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        replyParm1_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.serverStreaming.ServerStreamingGrpc.internal_static_serverStreaming_ServerStreamingReply_descriptor;
      }

      public io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply getDefaultInstanceForType() {
        return io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply.getDefaultInstance();
      }

      public io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply build() {
        io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply buildPartial() {
        io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply result = new io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply(this);
        result.replyParm1_ = replyParm1_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply) {
          return mergeFrom((io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply other) {
        if (other == io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply.getDefaultInstance()) return this;
        if (!other.getReplyParm1().isEmpty()) {
          replyParm1_ = other.replyParm1_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object replyParm1_ = "";
      /**
       * <code>string ReplyParm1 = 1;</code>
       */
      public java.lang.String getReplyParm1() {
        java.lang.Object ref = replyParm1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          replyParm1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ReplyParm1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReplyParm1Bytes() {
        java.lang.Object ref = replyParm1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          replyParm1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ReplyParm1 = 1;</code>
       */
      public Builder setReplyParm1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        replyParm1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ReplyParm1 = 1;</code>
       */
      public Builder clearReplyParm1() {
        
        replyParm1_ = getDefaultInstance().getReplyParm1();
        onChanged();
        return this;
      }
      /**
       * <code>string ReplyParm1 = 1;</code>
       */
      public Builder setReplyParm1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        replyParm1_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:serverStreaming.ServerStreamingReply)
    }

    // @@protoc_insertion_point(class_scope:serverStreaming.ServerStreamingReply)
    private static final io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply();
    }

    public static io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerStreamingReply>
        PARSER = new com.google.protobuf.AbstractParser<ServerStreamingReply>() {
      public ServerStreamingReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerStreamingReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerStreamingReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerStreamingReply> getParserForType() {
      return PARSER;
    }

    public io.grpc.serverStreaming.ServerStreamingGrpc.ServerStreamingReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serverStreaming_ServerStreamingRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serverStreaming_ServerStreamingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serverStreaming_ServerStreamingReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serverStreaming_ServerStreamingReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025serverStreaming.proto\022\017serverStreaming" +
      "\".\n\026ServerStreamingRequest\022\024\n\014RequsetPar" +
      "m1\030\001 \001(\t\"*\n\024ServerStreamingReply\022\022\n\nRepl" +
      "yParm1\030\001 \001(\t2\203\001\n\026ServerStreamingService\022" +
      "i\n\023ServerStreamingCall\022\'.serverStreaming" +
      ".ServerStreamingRequest\032%.serverStreamin" +
      "g.ServerStreamingReply\"\0000\001B.\n\027io.grpc.se" +
      "rverStreamingB\023ServerStreamingGrpcb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_serverStreaming_ServerStreamingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_serverStreaming_ServerStreamingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serverStreaming_ServerStreamingRequest_descriptor,
        new java.lang.String[] { "RequsetParm1", });
    internal_static_serverStreaming_ServerStreamingReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_serverStreaming_ServerStreamingReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serverStreaming_ServerStreamingReply_descriptor,
        new java.lang.String[] { "ReplyParm1", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
